language: go
sudo: false

go:
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $GOPATH/bin/goveralls -service=travis-ci
