language: go
go:
  - tip
before_install:
  - go get github.com/golang/lint/golint
  - go get -t -v ./...
script:
  - golint ./...
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: change
